theme: jekyll-theme-cayman
<h1>***TREMBLAY-en-FRANCE***</h1>


<p>Tremblay-en-France est une commune française située dans le département de la Seine-Saint-Denis, en région Île-de-France.<p>

<p>Ses habitants sont appelés les Tremblaysiens.<p>


<h2>Géographie</h2>


<h3>Localisation</h3>


<p>Tremblay-en-France est la commune la plus vaste du département de la Seine-Saint-Denis avec ses 2 244 hectares. Située à 25 km de Paris, elle est limitée par le Val-d'Oise au Nord-Ouest et la Seine-et-Marne à l'Est. Tremblay qui culmine à une altitude moyenne de 85 m au Vieux-Pays et à 60 m sur les rives de l'Ourcq, appartient géographiquement à la Plaine de France qui est découpée par les vallées de la Marne, de la Seine et de l'Oise.<p>


<h2>Politique et administration</h2>


<h3>Intercommunalité</h3>


<p>La commune faisait partie depuis 2010 de la communauté d'agglomération Terres de France.

<p>Dans le cadre de la mise en œuvre de la volonté gouvernementale de favoriser le développement du centre de l'agglomération parisienne comme pôle mondial est créée, le 1er janvier 2016, la métropole du Grand Paris (MGP), à laquelle la commune a été intégrée18.<p>

<p>La loi portant nouvelle organisation territoriale de la République du 7 août 2015 (Loi NOTRe) prévoit également la création le 1er janvier 2016 d'établissements publics territoriaux (EPT), qui regroupent l'ensemble des communes de la métropole à l'exception de Paris, et assurent des fonctions de proximité en matière de politique de la ville, d'équipements culturels, socioculturels, socio-éducatifs et sportifs, d'eau et assainissement, de gestion des déchets ménagers et d'action sociale, et exerçant également les compétences que les communes avaient transférées aux intercommunalités supprimées<p>

<p>Tremblay-en-France fait donc partie depuis le 1er janvier 2016 de l'établissement public territorial Paris Terres d'Envol, créé par un décret du 11 décembre 201619 et qui regroupe les cinq communes adhérant au SEAPFA (dont les trois communes membres de Terres de France) ainsi que les trois communes qui faisaient partie de la communauté d'agglomération de l'aéroport du Bourget.<p>

<p>Elle est également membre du syndicat d'équipement et d'aménagement des Pays de France et de l'Aulnoye (SEAPFA).<p>

***Export HTML***
